org: kiady67
app: kiady-http-api
service: kiady-http-api
frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-python-requirements

custom:
  stage: ${opt:stage, self:provider.stage, "dev"}

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment: ${file(./env.yml):${self:custom.stage}}

functions:
  login:
    handler: src/login.login
    events:
      - httpApi:
          path: /login
          method: post

  get_task:
    handler: src/task.get_task
    events:
      - httpApi:
          path: /task
          method: post


  create_task:
    handler: src/task.create_task
    events:
      - httpApi:
          path: /task/create
          method: post

  update_task:
    handler: src/task.update_task
    events:
      - httpApi:
          path: /task/update
          method: post

  delete_task:
    handler: src/task.delete
    events:
      - httpApi:
          path: /task/delete_task
          method: post

  static_function_test:
    handler: src/static_function.static_function_test
    events:
      - httpApi:
          path: /static_function
          method: post