org: kiady67
app: kiady-http-api
service: kiady-http-api
frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-python-requirements


provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  login:
    handler: src/login.login
    events:
      - httpApi:
          path: /login
          method: post

  is_owner_task:
    handler: src/task.is_owner_test
    events:
      - httpApi:
          path: /task/is_owner
          method: post

  create_task:
    handler: src/task.create_task
    events:
      - httpApi:
          path: /task/create_task
          method: post
    package:
      include:
        - /login.py

  static_function_test:
    handler: src/static_function.static_function_test
    events:
      - httpApi:
          path: /static_function
          method: post